### ISSUE TITLE
json url is not working

### ISSUE THREAD

**Issue by nobutsta** [eyeofchaos/eocjsNewsticker#1]
I used it on v0.3 with no problem. But now upgrade to 0.4.1. It error with "Error: No data found. Check your remote source". Same source option, same json structure. Any suggestion?

**Comment by eyeofchaos** [comment]
Hi,

you _probably_ used an Array in your JSON source.
I changed the code, tested it and made a new release.

Please let me know, if v0.4.2 fixes your issue.

Best wishes
Dieter

**Comment by nobutsta** [comment]
So why the same json is working with the version before if it's not cover?

**Comment by nobutsta** [comment]
It's working by the way. Thanks for the update ^^

**Comment by nobutsta** [comment]
Is there any future option that can pause on mouse hover?

**Comment by eyeofchaos** [comment]
Thanks for your reply.

I'll consider "stop-on-mouseover" for a future release.

Best wishes
Dieter
